var mongoose = require('mongoose');

// Note that this schema does not design to optimize memory and query.
var UserSchema = mongoose.Schema({
  participantId: {type: String, require: true},
  firstName: String,
  lastName: String,
  gender: String,
  examType: {type: String, enum: ["A", "B", "C"]},
  question1: String,
  question2: String,
  question3: String,
  question4: String,
  question5: String,
  question6: String,
  question7: String,
  question8: String,
  question9: String,
  question10: String,
  question11: String,
  question12: String,
  question13: String,
  question14: String,
  question15: String,
  time1: Number,
  time2: Number,
  time3: Number,
  time4: Number,
  time5: Number,
  time6: Number,
  time7: Number,
  time8: Number,
  time9: Number,
  time10: Number,
  time11: Number,
  time12: Number,
  time13: Number,
  time14: Number,
  time15: Number,
})

module.exports = mongoose.model("User", UserSchema);
